language: minimal

services: docker

env: Dimg=lorabasics/basicmac-test; Dname=basicmac-test

before_install:
- sudo chown -R 1000:1000 $TRAVIS_BUILD_DIR
- docker run -d --name $Dname -v $TRAVIS_BUILD_DIR:/home/nonprivuser/travis -w /home/nonprivuser/travis $Dimg tail -f /dev/null
- export Dcmd="docker exec -t $Dname bash -c"

install:
# nothing to install

script:
# all commands must be quoted
- $Dcmd "make -C basicloader && cd projects/ex-join && make && VARIANT=simul make test"
